language: node_js
os:
  - linux
node_js:
  - "10.14"
  - "8.14"
  - "6.15"
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - 'if [ -n "${COVER}" ]; then npm run cover ; fi'
matrix:
  include:
    - node_js: 10.14
      env: COVER=true
    - node_js: 8.14
    - node_js: 6.15