language: node_js
os:
  - linux
node_js:
  - "12"
  - "13"
before_install:
  - nvm install-latest-npm
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - if [ -n "${COVER}" ]; then npm run cover ; fi
matrix:
  include:
    - node_js: 12
    - node_js: 10
      env: COVER=true
    - node_js: 8
